pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building..'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
				katalon -noSplash  -runMode=console -projectPath="LookAndBookTest/LookAndBookTest.prj" -retry=0 -testSuitePath="Test Suites/Authentification" -executionProfile="default" -browserType="Web Service"
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}